name: Test

on:
  push:
    branches:
      - master
      - 'dev/*'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * 0-4" # 08:00 JST, Monday to Friday

env:
  PLUGIN_PATH: plugins/redmica_ui_extension
  RAILS_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - redmine-repository: 'redmine/redmine'
            redmine-version: 'master'
            ruby-version: '4.0'
          - redmine-repository: 'redmica/redmica'
            redmine-version: 'stable-4.1'
            ruby-version: '3.4'

    steps:
    - name: Set up Redmine
      uses: hidakatsuya/action-setup-redmine@v4.0.0
      with:
        repository: ${{ matrix.redmine-repository }}
        version: ${{ matrix.redmine-version }}
        ruby-version: ${{ matrix.ruby-version }}
        database: postgres:14

    - name: Check out plugin
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        path: ${{ env.PLUGIN_PATH }}

    - name: Set up plugin
      run: bundle install

    - name: Install Playwright dependencies
      run: |
        npm --prefix "$PLUGIN_PATH" install
        npx --prefix "$PLUGIN_PATH" playwright install chromium
        npx --prefix "$PLUGIN_PATH" playwright install-deps

    - name: Run tests
      run: bundle exec rake test TEST="$PLUGIN_PATH/test"
